# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TitUI_progress_copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 439)
        MainWindow.setMaximumSize(QtCore.QSize(517, 439))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tubiao/Public.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow{\n"
"\n"
"background-color:#ffffff;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(210, 50, 91, 31))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(390, 50, 91, 31))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(30, 80, 91, 31))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(120, 50, 91, 31))
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(300, 50, 91, 31))
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 270, 511, 41))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(30, 50, 91, 31))
        self.pushButton_20.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 10, 59, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 20, 51, 20))
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setGeometry(QtCore.QRect(300, 80, 91, 31))
        self.pushButton_28.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_28.setObjectName("pushButton_28")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 20, 47, 20))
        self.label.setStyleSheet("QLabel{\n"
"\n"
"color:#ffffff;\n"
"\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setGeometry(QtCore.QRect(120, 80, 91, 31))
        self.pushButton_29.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setGeometry(QtCore.QRect(390, 80, 91, 31))
        self.pushButton_31.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_32.setGeometry(QtCore.QRect(30, 110, 91, 31))
        self.pushButton_32.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_33.setGeometry(QtCore.QRect(390, 110, 91, 31))
        self.pushButton_33.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setGeometry(QtCore.QRect(210, 80, 91, 31))
        self.pushButton_30.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_34.setGeometry(QtCore.QRect(210, 110, 91, 31))
        self.pushButton_34.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_35.setGeometry(QtCore.QRect(300, 110, 91, 31))
        self.pushButton_35.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_36.setGeometry(QtCore.QRect(210, 140, 91, 31))
        self.pushButton_36.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_37.setGeometry(QtCore.QRect(120, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_37.setObjectName("pushButton_37")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(300, 150, 201, 16))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"background-color:rgb(253, 253, 253)\n"
"}\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(210, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"\n"
"color:#ff0000;\n"
"\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(210, 290, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"\n"
"color:#ff0000;\n"
"\n"
"}")
        self.label_6.setObjectName("label_6")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(30, 320, 91, 31))
        self.pushButton_21.setStyleSheet("QPushButton{\n"
"border-image: url(:/greenbutton/greenbutton.png);\n"
"color:#ffffff;\n"
"font：15px;\n"
"}\n"
"QPushButton:hover{\n"
"color:#070707;\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 150, 121, 20))
        self.comboBox.setObjectName("comboBox")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, 150, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lily TNB Auto Tool"))
        Project_list=["Ares1","Ares2_AMD","Ares2_Intel","Eagle","Hera2","Hotrod","kylo1","kylo2","L13_Intel","L13_AMD","L13_2_Intel","L13_2_AMD","L1415_Intel","L1415_AMD","L1415_2_Intel","L1415_2_AMD","LBB1","LBB2","LCE1","LCH1","LCH2","LCH3","LPM1","LPM2","LPM3","Leia","LTS1","LTS2","LRV2","LRV3","Lynx1","Lynx2","Zeus2","Zeus3"]
        self.comboBox.setMaxVisibleItems(7)
        self.comboBox.addItems(Project_list)

        self.pushButton_12.setText(_translate("MainWindow", " AC S4"))
        self.pushButton_13.setText(_translate("MainWindow", " FSU"))
        self.pushButton_15.setText(_translate("MainWindow", " S5"))
        self.pushButton_17.setText(_translate("MainWindow", "AC MS"))
        self.pushButton_18.setText(_translate("MainWindow", " AC WB"))
        self.pushButton_20.setText(_translate("MainWindow", "环境设置"))
        self.label_4.setText(_translate("MainWindow", "输入圈数："))
        self.pushButton_28.setText(_translate("MainWindow", "DC WB"))
        self.pushButton_29.setText(_translate("MainWindow", "  DC MS"))
        self.pushButton_31.setText(_translate("MainWindow", "WinLR FSU"))
        self.pushButton_32.setText(_translate("MainWindow", "WinLR S5"))
        self.pushButton_33.setText(_translate("MainWindow", "Tool copy"))
        self.pushButton_30.setText(_translate("MainWindow", "DC S4"))
        self.pushButton_34.setText(_translate("MainWindow", "LOG收集"))
        self.pushButton_35.setText(_translate("MainWindow", "LOG查看"))
        self.pushButton_36.setText(_translate("MainWindow", "机器注册"))
        self.pushButton_37.setText(_translate("MainWindow", " WiLRCombine"))
        self.label_5.setText(_translate("MainWindow", "ATS区域"))
        self.label_6.setText(_translate("MainWindow", "AZ区域"))
        self.pushButton_21.setText(_translate("MainWindow", "账户切换"))
        self.label_7.setText(_translate("MainWindow", "选择专案名称:"))
import bottombackgound_rc
import greenbutton_rc
import tubiao_rc
import yellowbutton_rc
